apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-u4b3
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0059-tenant/tkrw-pr712-0075-0059-app/devfile-sample-u4b3@sha256:21056967fa3c17272caa5eb1b5f2a706b9fdf9b7265824092e69f35d9d74f0e0
        name: my-nodejs
        resources: {}
status: {}
